### ISSUE TITLE
compare: too many failed files?

### ISSUE THREAD

**Issue by ZingBallyhoo** [ZingBallyhoo/OverwatchDataManager#2]
Needs investigation

**Comment by ZingBallyhoo** [comment]
BLTEDecoderException: not enough data: 8

**Comment by ZingBallyhoo** [comment]
8

**Comment by ZingBallyhoo** [comment]
Sample fail files:
 * 0000000023D4.004
 * 000000040A0C.03F

It is calling  CASCExplorer.CASCHandler.OpenFileOnline?

**Comment by ZingBallyhoo** [comment]
Real not bugged fail:
```
CASCExplorer.BLTEDecoderException: frame header mismatch (bad BLTE file)
   at CASCExplorer.BLTEStream.Parse(MD5Hash md5)
   at CASCExplorer.BLTEStream..ctor(Stream src, MD5Hash md5)
   at CASCExplorer.CASCHandlerBase.OpenFile(MD5Hash key)
   at CASCExplorer.CASCHandler.OpenFile(UInt64 hash)
   at PyOWLib.Utils.<>c__DisplayClass3_0.<compareFiles>b__0(Int64 x)
files\Win_SPWin_RDEV_LenUS_EExt\004\00000000DB9E.004 failed

**Comment by ZingBallyhoo** [comment]
Bug is due to Paralell.For
