### ISSUE TITLE
CASCManager.save_file random freezing

### ISSUE THREAD

**Issue by ZingBallyhoo** [ZingBallyhoo/OverwatchDataManager#6]
Unknown cause. Unable to reliably reproduce. Happening with a fresh run of manager.py

https://github.com/ZingBallyhoo/OverwatchDataManager/blob/master/manager.py#L443

https://github.com/ZingBallyhoo/OverwatchDataManager/blob/master/pyow/casc.py#L122

CTRL+C does nothing.

**Comment by ZingBallyhoo** [comment]
Python process will use ~5mb/s network while hanging

**Comment by ZingBallyhoo** [comment]
CTRL+C responds after 30 seconds ish

**Comment by ZingBallyhoo** [comment]
This is probably what is happening:

```
CASCExplorer.BLTEDecoderException: not enough data: 8
   at CASCExplorer.BLTEStream.Parse(MD5Hash md5)
   at CASCExplorer.BLTEStream..ctor(Stream src, MD5Hash md5)
   at CASCExplorer.CASCHandlerBase.OpenFileOnlineInternal(IndexEntry idxInfo, MD5Hash key)
   at CASCExplorer.CASCHandler.OpenFileOnline(MD5Hash key)
   at CASCExplorer.CASCHandlerBase.OpenFile(MD5Hash key)
   at CASCExplorer.CASCHandler.OpenFile(UInt64 hash)
   at PyOWLib.Utils.<>c__DisplayClass3_0.<compareFiles>b__0(Int64 x)
```
(from #2)

**Comment by ZingBallyhoo** [comment]
Test run just froze for 3 minutes, resumed, and froze again

**Comment by ZingBallyhoo** [comment]
Nevermind, I was running in an admin cmd, and it put the version folder in `C:/Windows/System32`.
Freezing problem was to do with Battle.net, I can't read what I myself wrote in the readme.
